apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'idea'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.diffplug.spotless'
apply plugin: 'jvm-test-suite'

sourceCompatibility = '21'

dependencyManagement {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:${property('spring-boot.version')}"
  }
}

configurations {
  compileOnly {
    extendsFrom annotationProcessor
  }
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-validation'

  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

  testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

spotless {
  format 'misc', {
    target '*.gradle', '*.md', '.gitignore'

    trimTrailingWhitespace()
    indentWithSpaces(2)
    endWithNewline()
  }
  java {
    importOrder()
    removeUnusedImports()
    indentWithSpaces(2)
    googleJavaFormat()
    formatAnnotations()
  }
  groovy {
    importOrder()
    excludeJava()
  }
}

tasks.withType(JavaCompile) {
  options.compilerArgs.add("-Xlint:deprecation")
  options.compilerArgs.add("-Xlint:unchecked")
  options.compilerArgs.add("-parameters")
}

testing {
  suites {
    test {
      useSpock('2.4-M1-groovy-4.0')
    }
  }
}
